from .ppil_tests import test_simple_goal_query
from .ppil_tests import test_simple_goal_query2
from .ppil_tests import test_simple_variable_query
from .ppil_tests import test_multi_variable_solutions
from .ppil_tests import test_find_bad_dog
from .ppil_tests import test_rule_sub
from .ppil_tests import test_rule_sub2
from .ppil_tests import test_multiple_var_query
from .ppil_tests import test_einstein_puzzle
from .ppil_tests import test_alternate_einstein_puzzle
