JSON_FORMAT_KEYS = ['predicate', 'fact']
ALLOWED_CONDITIONS = ['and', ',', 'or', ';']
ALLOWED_CONDITIONS_TYPES = ['predicate', 'condition']
CONDITION_SEPARATORS = ['=', '>', 'is', '<', '=<', '>=', '=:=', r'=\=']
AVAILABLE_ENDPOINTS = ['prolog-to-json', 'json-to-prolog', 'json-execute', 'prolog-execute']
STRING_SEPARATORS = ['"', '\'']
